# Generated by Django 4.1.4 on 2022-12-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_dht11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
